# Generated by Django 3.2 on 2022-08-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.IntegerField()),
                ('bus_name', models.CharField(max_length=30)),
                ('bus_start', models.CharField(max_length=30)),
                ('bus_dest', models.CharField(max_length=30)),
                ('bus_route', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('reaching_time', models.TimeField()),
                ('total_seats', models.IntegerField()),
            ],
            options={
                'db_table': 'Bus details',
            },
        ),
        migrations.CreateModel(
            name='BusPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact_number', models.IntegerField()),
                ('on_which_bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bus.bus')),
            ],
        ),
    ]
