# Generated by Django 3.2.10 on 2022-08-16 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220816_1519'),
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
        ),
        migrations.AlterModelTable(
            name='bus',
            table='Bus_details',
        ),
        migrations.DeleteModel(
            name='BusPerson',
        ),
    ]
