# Generated by Django 3.2.10 on 2022-08-16 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField()),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('address', models.CharField(default='', max_length=40)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2022, 8, 16, 15, 59, 47, 220997))),
                ('is_manager', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
            ],
        ),
    ]
