# Generated by Django 3.2.10 on 2022-08-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField()),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('is_superuser', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
