# Generated by Django 3.2.10 on 2022-08-16 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 16, 20, 3, 562387)),
        ),
    ]
